name: Release 

on:
  push:
    tags:
      - 'v*'
env:
  CARGO_TERM_COLOR: always

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: ubuntu-latest
    needs: [linux-tagged-release, windows-tagged-release]

    steps:
    - name: Download Linux Artifacts
      uses: actions/download-artifact@v2
      with:
        name: linux-ci-example.tar.gz
    - name: Download Windows Artifacts
      uses: actions/download-artifact@v2
      with:
        name: windows-ci-example.tar.gz
    - name: Publish artifacts 
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        files: |
          linux-ci-example.tar.gz
          windows-ci-example.zip

  linux-tagged-release:
    name: "Linux Tagged Release"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Static config
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: cargo build --target x86_64-unknown-linux-musl --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Compress 
      run: tar cvzf linux-ci-example.tar.gz -C /home/runner/work/ci-example/ci-example/target/x86_64-unknown-linux-musl/release ci-example
    - name: Artifact 
      uses: actions/upload-artifact@v2 
      with:
        name: linux-ci-example.tar.gz 
        path: linux-ci-example.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows-tagged-release:
    name: "Windows Tagged Release"
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Static config
      shell: powershell
      run: set-variable RUSTFLAGS "-C target-feature=+crt-static" 
    - name: Check configuration
      shell: powershell
      run: $env:RUSTFLAGS
    - name: Build
      shell: powershell
      run: cargo build --verbose --release 
    - name: Run tests
      shell: powershell
      run: cargo test --verbose
    - name: Compress 
      shell: powershell
      run: Compress-Archive README.md windows-ci-example.zip 
    - name: Artifact 
      uses: actions/upload-artifact@v2 
      with:
        name: windows-ci-example.zip 
        path: windows-ci-example.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

