name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - name: List
      run: ls -larth /home/runner/work/ci-example/ci-example/target/release
    - name: Run tests
      run: cargo test --verbose
    - name: Release
      uses: actions/upload-artifact@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: /home/runner/work/ci-example/ci-example/target/release/ci-example
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


